### ISSUE TITLE
HW: version 1.5 of RaSCSI has ACT signal miswired

### ISSUE THREAD

**Issue by akuker** [akuker/RASCSI#10]
Version 1.5 of the RaSCSI "68kmla" version has an incorrect connection. Pin 1 should be connected to the "ACT" signal, instead of the PI-ACK signal.

![image](https://user-images.githubusercontent.com/34318535/87188720-ef206180-c2b4-11ea-94c5-b9278776269c.png)

Workaround:

Cut the trace of ACT running to pin 1 of U3. Scrape off some solder mask on the side near the via.
![2020-07-10-135902_3840x1080_scrot](https://user-images.githubusercontent.com/34318535/87190644-70c5be80-c2b8-11ea-9316-876f9b09584e.png)

Solder a jumper wire from the trace to Pin 7 of the Raspberry Pi GPIO header.
![2020-07-10-135821_3840x1080_scrot](https://user-images.githubusercontent.com/34318535/87190638-6d323780-c2b8-11ea-902d-791b1b6b68f1.png)

**Comment by akuker** [comment]
Tagged as "won't fix". When the next batch of boards (if ever) are ordered, this should be fixed.

**Comment by phrax0** [comment]
With the development of the 1.6 board addressing this issue, we can close #10 now.  Also, thanks for doing the 1.6 board akuker!

**Comment by akuker** [comment]
Agreed!
