### ISSUE TITLE
Code is not 64 bit clean

### ISSUE THREAD

**Issue by uweseimet** [akuker/RASCSI#126]
Compiler warnings indicate that there are issues with 64 bit environments. Ubuntu is available in a 64 bit version for the Raspberry Pi, and it would be nice if the software could be run on this OS.
The main issues appears to be gpiobus::bcm_host_get_peripheral_address, which only supports 32 bit hardware.

**Comment by uweseimet** [comment]
@akuker Regarding the gpiobus::bcm_host_get_peripheral_address problem there does not seem to be any newer code by Broadcom that supports 64 bit. But I assume that you know the address range occupied by your hardware in a 64 bit environment, don't you? Which address range is it?

**Comment by uweseimet** [comment]
@akuker Would be great if you could comment on my question above.

**Comment by akuker** [comment]
Hi @uweseimet - Unfortunately, I do not. I haven't really invested any time in researching what it would take to go to 64-bit. 

Are there benefits that we'd get by going to 64 bit? My thinking is that the GPIO reads/writes are probably the current bottleneck. I'm guessing going to 64-bit won't help that.

(Someday we will have to go to 64-bit, if/when the Raspberry Pi foundation drops 32 bit support)

**Comment by akuker** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?t=244031

**Comment by uweseimet** [comment]
@akuker There is a benefit at least for those who would like to use their Pi not only for RaSCSI but additionally for other things, where a 64 bit OS may be useful. With 4 GB or more memory in your Pi 64 bit make sense. There is already a 64 bit Ubuntu for the Pi, by the way.
