### ISSUE TITLE
web interface only shows APPLE GENUINE format disks

### ISSUE THREAD

**Issue by DIYsciBorg** [akuker/RASCSI#156]
# Info

- Which version of Pi are you using:  3B+
- Which github revision of software:  v21.05.01
- Which board version:  aibomnet Adpter Lite Rev 297
- Which computer is the RaSCSI connected to: X68000 Expert (SaSI interface)

# Describe the issue
after using the web tool to create an XM6 SaSI image of 20 or 40 MB, I confirmed that the file is created in /images. However, even after refreshing the url, the image does not show up in the image file management list.  Same is true for XM6.

In fact, I tried with ALL other formats.  ONLY .hda files appear in the Image File Management list. Yet all created files appear in the /images folder.

ls output:
pi@raspberrypi:~/images $ ls
600MB.hda   NEC.hdn     SCSI_40.hds  wapple.hda  XM6SCSI.hds
Anex86.hdi  SASI_1.hdf  T98Next.nhd  XM6MO.mos

Web interface:

File | Size | Actions
-- | -- | --
600MB.hda
wapple.hda

**Comment by deetzi** [comment]
To get other types listed you can edit src/web/rasctl_cmd.py
Line 8:

valid_file_types = ["*.hda", "*.iso", "*.cdr", "*.zip"]

I changed "*.hda" to "*.hd?" though you can add other extensions to the list.

Other file that needs editing is src/web/web.py
Line 134:
    elif file_name.lower().endswith(".hda");

Changed to:
    elif file_name.lower().endswith(".hda") or file_name.lower().endswith(".hds"):

Allowed me to mount .hds files. You'll have to add additional or statements for other extensions you want to mount.

Then a quick sudo systemctl restart rascsi-web.service to reload.
