### ISSUE TITLE
DaynaPort and bridge devices should not inherit from Disk

### ISSUE THREAD

**Issue by uweseimet** [akuker/RASCSI#179]
In order to improve code quality and maintainability SCSIDaynaPort and Bridge should not inherit from Disk, because they are not disk-like devices. The correct base clases are PrimaryDevice or ModePageDevice.

**Comment by akuker** [comment]
@uweseimet - I agree. It should probably be a new "Controller" class.

**Comment by uweseimet** [comment]
@akuker Rather a Devices class, which contains all Disk attributes that are not specific to disks but to devices in general. I created https://github.com/akuker/RASCSI/issues/186 for this and https://github.com/akuker/RASCSI/tree/feature_device_base_class is addressing this.

**Comment by uweseimet** [comment]
Replaced by https://github.com/akuker/RASCSI/issues/663.
