### ISSUE TITLE
Setup build environment for Bare Metal version of RaSCSI

### ISSUE THREAD

**Issue by akuker** [akuker/RASCSI#18]
Set up makefiles and pull together some documentation for how to make the bare-metal RaSCSI build, described here:
http://retropc.net/gimons/rascsi_bm/index.html

This should be included in the regression testing (once that is available).

**Comment by akuker** [comment]
Note that the complete source code for the bare metal version was only made available by Gimons with version 1.50.

**Comment by uweseimet** [comment]
@akuker This issue has become obsolete, hasn't it?

**Comment by akuker** [comment]
Agree!
