### ISSUE TITLE
Unification of the various device types

### ISSUE THREAD

**Issue by uweseimet** [akuker/RASCSI#181]
Currently there are several sets of device types:

-  SASI_HD, SCSI_HD, MO, CD, BR, NUVOLINK, DAYNAPORT (used internally by rascsi and also defined in the protobuf interface)
- SCHD (either SASI_HD or SCSI_HD, depending on a boolean in Disk.cpp), SCMO, SCCD, SCBR, SCNL, SCDP (all used by rascsi and rasctl)
- hd, mo, cd, bridge, daynaport (used by rasctl as an argument for the TYPE command line setting)

This is is not very transparent. Instead, internally only one type should be used. Any client can map this type to whatever display representation this client requires.

Suggested solution: Use these types everywhere:

- SAHD (non-removable SASI hard disk drive)
- SCHD (non-removable SCSI hard disk drive)
- SCRM (removable SCSI hard disk drive, potential resolution for https://github.com/akuker/RASCSI/issues/6)
- SCMO
- SCCD
- SCBR
- SCNL (Is this a type that is still under development? There are only a few code fragments.)
- SCDP

rascsi/rasctl use these types (just like now) in the device list display. In order to still support the hd, mo, cd, bridge, daynaport device type rasctl can map these type accordingly. Or, even better, directly use the types above. (This might not be backwards compatible.)

@akuker This change is not much of an effort, but will make type handling much easier. Any comments?

**Comment by akuker** [comment]
@uweseimet - Nuvolink is abandoned. We could eliminate all references from the code at some point. That was the first attempt at SCSI Ethernet capability. However, the Nuvolink requires RESELECT, which the RaSCSI software architecture does not easily support. Since DaynaPort is working, there is no need to support Nuvolink.
