### ISSUE TITLE
Modular device implementation approach (dynamic loading of devices)

### ISSUE THREAD

**Issue by uweseimet** [akuker/RASCSI#185]
When a new device is created, based on its type the respective implementation module should be loaded on demand. Most likely the DeviceFactory class will have to load the module.

**Comment by uweseimet** [comment]
@akuker This ticket is mainly meant to be an incenctive for improving modularity. But I'm find with closing it.

**Comment by akuker** [comment]
I have no objections with improving modularity. Also no objections with dynamic libraries if it helps solve a problem :)

**Comment by uweseimet** [comment]
@akuker In this case let's keep it open for now. The idea was, that if you can implement dynamic loading of devices you have reached a decent level of modulariy, as far as devices types are concerned. We are not yet there, but https://github.com/akuker/RASCSI/pull/662 is a step forward.

**Comment by uweseimet** [comment]
Closed as part of a ticket cleanup. There are too many tickets already, a lot of them half-started or abandoned or in some other kind of undefined state.
