### ISSUE TITLE
Add meaningful logging functionality

### ISSUE THREAD

**Issue by akuker** [akuker/RASCSI#19]
Currently, RaSCSI doesn't output very much useful information.

The code should be updated so different logging levels are available (TRACE, DEBUG, INFO, WARNING, etc) that can be configured at startup (or, even better... at runtime).

https://github.com/gabime/spdlog seems like a good candidate to start with. 

This work was started on https://github.com/akuker/RASCSI/tree/logging_improvements

**Comment by uweseimet** [comment]
@akuker Is there still anything to be done for this issue?

**Comment by akuker** [comment]
Nope - this can be closed.
