### ISSUE TITLE
RaSCSI crashes when MacOS reboots

### ISSUE THREAD

**Issue by akuker** [akuker/RASCSI#2]
This issue was observed using MacOS 8.1, but likely applies to other versions as well.

When the Mac starts the reboot process, it will send a Flush command to RaSCSI that is not supported. This causes RaSCSI to immediately crash and will cause the Mac to freeze (before it reboots). 

To recover from this situation, you need to re-start RaSCSI.

    Received an invalid flush command 15!!!!!
    rascsi: disk.cpp:7864: void SASIDEV::FlushUnit(): Assertion `0' failed.
    make: *** [Makefile:108: run] Aborted

**Comment by akuker** [comment]
Some observations:
While the drive is in DataOut mode, the initiator is sending a mode select command with the page code 0x08.

From void FASTCALL SASIDEV::FlushUnit().......
  Operation Code: [15]
  Logical Unit 0, PF 1, SP 0 [10]
  Reserved: 00
  Reserved: 00
  Parameter List Len 18
  Reserved: 00
  Ctrl Len: 00000000

From SCSIHD::ModeSelect()......
Received page code 8 with length 10
     08 0A 00 00 00 00 00 00 00 00 00 00

Mode Page Code 8 is defined in this old Sony interface manual, but the size of the command doesn't match.
http://www.bitsavers.org/pdf/sony/cdrom/Sony_CDU-541_SCSI_Interface_Manual_Mar1990.pdf

For now, updating RaSCSI to accept and ignore Mode Page Code 8 without throwing an error.

**Comment by akuker** [comment]
I'm going to consider this fix sufficient for now. Issue #1 will need to clean-up the Mac driver-specific commands. Everything seems to still work when this mode select command is ignored (with the patched driver)

**Comment by uweseimet** [comment]
@akuker Can you please verify whether this issue still exists? This issue looks very strange, and the work around is not such a good solution. (I have never seen the warning from the work-around, by the way.)
In order to test this you would have to remove the work-around in scsihd.cpp.

**Comment by akuker** [comment]
> Can you please verify whether this issue still exists? This issue looks very strange, and the work around is not such a good solution.

This is an old one! I'm a little swamped at work right now, but will try it out as soon as I get a chance.

**Comment by uweseimet** [comment]
@akuker @rdmark Half a year has gone ;-). I suggest to close this ticket and remove the related debug code. There were so many code changes anyway that it's not clear whether this ticket is still valid.

**Comment by akuker** [comment]
No objections closing this. Thank you for doing some backlog grooming, @uweseimet !
