### ISSUE TITLE
Support for STANDARD boards in easyinstall.sh

### ISSUE THREAD

**Issue by rdmark** [akuker/RASCSI#225]
Make it possible to use easyinstall.sh for STANDARD boards in addition to FULLSPEC.
One way to implement it to have the script parse a parameter, e.g. -c | --connect_type
When no parameter is specified, fall back to FULLSPEC

**Comment by rdmark** [comment]
Resolved with https://github.com/akuker/RASCSI/pull/227

**Comment by akuker** [comment]
@rdmark Are there folks out there who are using standard boards?

**Comment by rdmark** [comment]
@akuker Apparently so, I helped someone yesterday in Discord with a Standard board.

**Comment by akuker** [comment]
Cool. I just saw that.

**Comment by rdmark** [comment]
Now merged into another PR https://github.com/akuker/RASCSI/pull/229
