### ISSUE TITLE
Handle MO .mos images

### ISSUE THREAD

**Issue by rdmark** [akuker/RASCSI#253]
Dumped MO (magneto-optical) images for the X68000 use a .mos file ending, as per the de-facto standard established by the XM6 emulator for X68000.
This ticket is to make sure we support creating, listing and attaching .mos files in the web ui.

References:
* https://mijet.eludevisibility.org/XM6%20Pro-68k/XM6%20Pro-68k.html
* https://www.6502man.com/Bricolages/X68000/CD_MO_Scsi_Device/X68000_MO_howToUse_WintoX68KtoWin.html
* http://retropc.net/gimons/rascsi/index.html (talks briefly about the MOS format)
* https://github.com/akuker/RASCSI/wiki/X68000#SCSI_MagnetoOptical_MO_Disks (English translation of the above)

Examples of supposedly valid .mos files:
* https://nfggames.com/forum2/index.php?topic=4917.0
* https://nfggames.com/X68000/

**Comment by rdmark** [comment]
Out of the gate, rascsi on develop has no problem recognizing .mos images. However, the one and only verified .mos dump that I've found so far is just a few 100 bytes too large for rascsi to be able to attach it -- 228518912 when rascsi expects 228518400.

**Comment by uweseimet** [comment]
Would anybody notice if the X68000 stuff was just discarded? I wonder whether this can be supported at all, as far as testing is concerned.

**Comment by rdmark** [comment]
Last I heard @akuker wasn't ready to discard X68k code. Agreed that testing is a challenge on that platform.

BTW, wasn't SCSI MO drives standard on NeXT machines as well? I'm pretty sure I saw someone mentioning using RaSCSI with their NeXT system.

**Comment by rdmark** [comment]
Current develop now recognizes .mos images on the back and frontend side: rascsi backend recognizes it as a SCMO device, while the frontend has it among the 'recognized file types'. 
At this point, I think creating mos images is out of scope, since noone on the dev team has an environment to validate the functionality further.

**Comment by uweseimet** [comment]
@rdmark One more note on this: I tried different MO drives in the past with my Atari, and at least with the Atari no special handling is needed. You just need a driver that supports optical drives and (depending on the medium) 2048 bytes per sector. Then you can use MO drives like any other removable media drive.
Using any .mos image with the Atari works fine. The only restriction is that rascsi limits the choice of available images sizes to what it assumes to be the size of real-world MO media.
