### ISSUE TITLE
Log Level in Web UI is not Correct

### ISSUE THREAD

**Issue by akuker** [akuker/RASCSI#263]
# Info
- Which version of Pi are you using: Any
- Which github revision of software: develop 1311317
- Which board version: All
- Which computer is the RaSCSI connected to: Any

# Describe the issue
In the Web GUI, the Server Log Level option menu should default to the log level. Right now, it looks like it just always defaults to "trace". 

I'm guessing this will take some updates in rasctl/rascsi to be able to retrieve the current log level.

**Comment by rdmark** [comment]
@akuker Good idea. Easy fix: https://github.com/akuker/RASCSI/pull/268

BTW, with this change do we want to perhaps remove the "Server log level:" line in the footer to keep it simple?

**Comment by rdmark** [comment]
Pushed a change with a simplified footer. Let me know what you think. I can revert the change if you liked the longer footer!

**Comment by akuker** [comment]
Looks great! Thank you @rdmark  for the updates!!!

Change was merged into develop
