### ISSUE TITLE
View the image extended properties from Web UI

### ISSUE THREAD

**Issue by akuker** [akuker/RASCSI#264]
# Enhancement
In the list of image files, I think it would be nice to be able to view the extended properties of the files. 

The ability to EDIT those files might be useful too. But since its kind of an advanced feature, we can probably leave that to the command line.

**Comment by rdmark** [comment]
@akuker A first stab at this here, using the same approach as 'device info': https://github.com/akuker/RASCSI/pull/270
Agreed that editing the properties should not be in the scope of rascsi-web.

**Comment by rdmark** [comment]
The first PR got lost in the ether, so made a new one here https://github.com/akuker/RASCSI/pull/290
