### ISSUE TITLE
rasctl should be able shut down RaSCSI

### ISSUE THREAD

**Issue by akuker** [akuker/RASCSI#3]
When running as a background service, there isn't an easy way too command RaSCSI to terminate. Suggest the following updates be made:
- A "-stop" command is added to rasctl that will command RaSCSI to terminate
- RaSCSI needs to be updated to exit gracefully when that command is received.

**Comment by akuker** [comment]
Note: I started working this in with issue #16.

**Comment by phrax0** [comment]
I don't know if this is in the dev tree, but if not, propose we start/stop the service with systemctl <start/stop> rascsi.  What are your thoughts on this?

**Comment by akuker** [comment]
Sort of.... systemctl stop rascsi doesn't do a graceful exit. It just kills the process. So, rascsi could be in the middle of a transaction, or saving cached data back to disk. 

The idea is that systemctl would call a 'rasctl' command to shutdown rascsi, isntead of just killing the process.
