### ISSUE TITLE
[Alphaserver] 8 LUNs reported for one drive

### ISSUE THREAD

**Issue by rdmark** [akuker/RASCSI#309]
As reported by pacjunk on Discord using recent develop code:

On an Alphaserver workstation, an attached hard drive image gets reported as 8 separate LUNs, all pointing at the same volume. So data written to one appears in all 8.

"Another issue, on the Alphaserver each drive is listed 8 times. So instead of seeing DKA200, it seems DKA200, 201, 202, 203, 204 etc. Now the drives do work and don't cause any problems, they just appear mutiple times. "

**Comment by rdmark** [comment]
[AXP.TXT](https://github.com/akuker/RASCSI/files/7310518/AXP.TXT)

So far they shared this analysis on the workstation side.

**Comment by uweseimet** [comment]
@Pacjunk The code location where rascsi currently reports an unsupported LUN was not executed. I updated the logging code, but would need a new log (debug level should be sufficient). Can you provide a new logfile based on the code in the lun_handling_update branch?

**Comment by Pacjunk** [comment]
OK, I'll do another rebuild (takes a long time!) and get back to you...

**Comment by Pacjunk** [comment]
Here you go...
[rascsi.log](https://github.com/akuker/RASCSI/files/7317292/rascsi.log)

**Comment by Pacjunk** [comment]
It looks like if I just do a "show device" at the console (no OS running), then it just sends multiple enquiries - no other traffic. The above log shows this plus the OS booting and using the drive, so harder to see the information.

```
Oct 10 12:12:00 raspberrypi RASCSI[402]: [2021-10-10 12:12:00.032] [debug] ++++ CMD ++++ virtual void SCSIDEV::Execute() Executing command $12
Oct 10 12:12:00 raspberrypi RASCSI[402]: [2021-10-10 12:12:00.032] [debug] virtual bool Disk::Dispatch(SCSIDEV*) Executing Inquiry ($12)
Oct 10 12:12:00 raspberrypi RASCSI[402]: [2021-10-10 12:12:00.033] [debug] ++++ CMD ++++ virtual void SCSIDEV::Execute() Executing command $12
Oct 10 12:12:00 raspberrypi RASCSI[402]: [2021-10-10 12:12:00.033] [debug] virtual bool Disk::Dispatch(SCSIDEV*) Executing Inquiry ($12)
Oct 10 12:12:00 raspberrypi RASCSI[402]: [2021-10-10 12:12:00.034] [debug] ++++ CMD ++++ virtual void SCSIDEV::Execute() Executing command $12
Oct 10 12:12:00 raspberrypi RASCSI[402]: [2021-10-10 12:12:00.034] [debug] virtual bool Disk::Dispatch(SCSIDEV*) Executing Inquiry ($12)
Oct 10 12:12:00 raspberrypi RASCSI[402]: [2021-10-10 12:12:00.034] [debug] ++++ CMD ++++ virtual void SCSIDEV::Execute() Executing command $12
Oct 10 12:12:00 raspberrypi RASCSI[402]: [2021-10-10 12:12:00.035] [debug] virtual bool Disk::Dispatch(SCSIDEV*) Executing Inquiry ($12)
Oct 10 12:12:00 raspberrypi RASCSI[402]: [2021-10-10 12:12:00.035] [debug] ++++ CMD ++++ virtual void SCSIDEV::Execute() Executing command $12
Oct 10 12:12:00 raspberrypi RASCSI[402]: [2021-10-10 12:12:00.035] [debug] virtual bool Disk::Dispatch(SCSIDEV*) Executing Inquiry ($12)
Oct 10 12:12:00 raspberrypi RASCSI[402]: [2021-10-10 12:12:00.036] [debug] ++++ CMD ++++ virtual void SCSIDEV::Execute() Executing command $12
Oct 10 12:12:00 raspberrypi RASCSI[402]: [2021-10-10 12:12:00.036] [debug] virtual bool Disk::Dispatch(SCSIDEV*) Executing Inquiry ($12)
Oct 10 12:12:00 raspberrypi RASCSI[402]: [2021-10-10 12:12:00.037] [debug] ++++ CMD ++++ virtual void SCSIDEV::Execute() Executing command $12
Oct 10 12:12:00 raspberrypi RASCSI[402]: [2021-10-10 12:12:00.037] [debug] virtual bool Disk::Dispatch(SCSIDEV*) Executing Inquiry ($12)
Oct 10 12:12:00 raspberrypi RASCSI[402]: [2021-10-10 12:12:00.038] [debug] ++++ CMD ++++ virtual void SCSIDEV::Execute() Executing command $12
Oct 10 12:12:00 raspberrypi RASCSI[402]: [2021-10-10 12:12:00.038] [debug] virtual bool Disk::Dispatch(SCSIDEV*) Executing Inquiry ($12)
Oct 10 12:12:00 raspberrypi RASCSI[402]: [2021-10-10 12:12:00.039] [debug] ++++ CMD ++++ virtual void SCSIDEV::Execute() Executing command $12
Oct 10 12:12:00 raspberrypi RASCSI[402]: [2021-10-10 12:12:00.039] [debug] virtual bool Disk::Dispatch(SCSIDEV*) Executing Inquiry ($12)
```

**Comment by Pacjunk** [comment]
It appears as if the host sends an inquiry for each LUN. e.g ID2,Lun0 ID2,Lun1 etc up to ID2,Lun7. RAscsi does not check the LUN number and just responds with the ID2 information 8 times!

**Comment by Pacjunk** [comment]
OK. I will update. Are there fields present for sublun? My devices appear as 200-207, so maybe the lun is always 0 and the sublun is the one changing.

**Comment by Pacjunk** [comment]
As you can tell, I don't know a lot about the internals of SCSI. I'm just looking around for things that *might* be an issue. Unfortunately some of these vintage systems don't want to conform to current SCSI standards...

**Comment by Pacjunk** [comment]
[lun_trace.log](https://github.com/akuker/RASCSI/files/7321589/lun_trace.log)

**Comment by Pacjunk** [comment]
OK. Let me know when you need more testing/logs. I assume @rdmark needs to close this ticket as he opened it?

**Comment by Pacjunk** [comment]
Just re-read everything and it all makes sense now. Thanks for tracking it down and educating me as well!
