### ISSUE TITLE
[VAXstation/Alphaserver] CD-ROM volume size reported as 1/4 of actual size

### ISSUE THREAD

**Issue by rdmark** [akuker/RASCSI#310]
As reported by pacjunk on Discord using recent develop code:

"Another thing I noticed is that the console on the machine reported the CD size as 170MB, when it should be 680. Looks like the SCSI inquiry is also assuming 2048 bytes instead of 512. Blocks/2048 will give a number 1/4 the size of blocks/512 and 170 is 1/4 of 680."

As a side effect, the OS seems to assume the drive is corrupted.

**Comment by rdmark** [comment]
@uweseimet This may be another side effect of the potential bug with RaSCSI handling of drives with non-standard block size.

**Comment by rdmark** [comment]
[VAX.TXT](https://github.com/akuker/RASCSI/files/7314029/VAX.TXT)

"If you look at the "Total blocks" near the beginning, it is 801808 for the real drive, and 200450 for the emulated. I assume rascsi is looking at the size of the iso and dividing by 2048 to get the number of blocks. Of course it should divide by 512. This is why the real size is 4 times that of the emulated one. From memory on these volumes the index file is, by default, stored in the middle of the drive, so when the OS tries to mount the drive it is looking for a block in the 400000 range and cannot find it."

**Comment by rdmark** [comment]
@uweseimet Verified that with this change, I was able to mount a DVD image using this as a test case: https://macintoshgarden.org/games/black-white-platinum-pack

**Comment by Pacjunk** [comment]
OK, I'm here (hopfully!). Updated my rascsi this morning and still having issues with CD ISO's reporting as 1/4 the size that they should be. The CDs I'm using should be 512/sector and rascsi seems to be using 2048/sector. Now I'm not really a C coder, but I had a quick look at scsicd.cpp and found this at line 434 & 475:

`SetBlockCount((DWORD)(size >> 11));`

From what I understand, this will shift right by 11 - in other words divide by 2048.

This seems to be the trouble that I am having. The number of blocks on the device is being presented as a quarter of the real value. I assume the above line needs to be modified to take into account the sector size.

I have some trace logs and a scsimon log of mounting a real CD if needed, but that above line looks highly suspicious to me!

**Comment by Pacjunk** [comment]
Is that "size >> GetSectorSize()" or should it be "size / GetSectorSize()" ??
Suppose it depends on whether that function returns the size (e.g. 512) or the number of bits (9)

**Comment by uweseimet** [comment]
@Pacjunk If I am not mistaken it returns the number of bits. (Cannot check right now.)

**Comment by Pacjunk** [comment]
Yeah, think its OK. There is another function GetSectorSizeinBytes. The HDD version uses your method, so should be all good. I will rebuild the branch now and give it a go....

Thanks,

**Comment by Pacjunk** [comment]
Well that is interesting. Tried it now and it says that there are 620134912 blocks on the disk. This is the number of bytes in the ISO file, so somehow it is setting 1 byte per block. Surprisingly the system doesn't care and mounts the disk anyway.
I think maybe the GetSectorSize() function is returning zero! (and thus not dividing at all)

**Comment by Pacjunk** [comment]
Bingo! It works...  Console and OS both report correct size. I can boot off the CD and copy files etc. All looks good. Now someone will have to test if it still works on the Mac! (Can't help there)

**Comment by rdmark** [comment]
Been testing be57e2 on a Mac and it seems to work fine reading from CD-ROM devices.

**Comment by Pacjunk** [comment]
`$ mount/over=id dkb100:
%MOUNT-I-WRITELOCK, volume is write locked
%MOUNT-I-MOUNTED, VAXVMS072 mounted on _$1$DKB100: (TESLA)
$ sh dev dkb100: /full

Disk $1$DKB100: (TESLA), device type RRD42, is online, allocated, deallocate on
    dismount, mounted, software write-locked, file-oriented device, shareable,
    error logging is enabled.

    Error count                    0    Operations completed                 27
    Owner process            "popop"    Owner UIC                      [SYSTEM]
    Owner process ID        00000124    Dev Prot            S:RWPL,O:RWPL,G:R,W
    Reference count                2    Default buffer size                 512
    Total blocks             1211201    Sectors per track                    25
    Total cylinders             6057    Tracks per cylinder                   8
    Allocation class               1

    Volume label         "VAXVMS072"    Relative volume number                0
    Cluster size                   9    Transaction count                     1
    Free blocks                 7956    Maximum files allowed            121000
    Extend quantity                5    Mount count                           1
    Mount status             Process    Cache name        "_$1$DKA200:XQPCACHE"
    Extent cache size             64    Maximum blocks in extent cache      795
    File ID cache size            64    Blocks currently in extent cache      0
    Quota cache size               0    Maximum buffers in FCP cache        764
    Volume owner UIC        [SYSTEM]    Vol Prot    S:RWCD,O:RWCD,G:RWCD,W:RWCD

  Volume Status:  ODS-2, subject to mount verification, file high-water marking,
      write-back caching enabled.

$  `

Total blocks is correct, fake geometry looks fine. Good performance boost over a real CD drive.

Thanks,
