### ISSUE TITLE
LUN requires deprecated LUN field and does not evaluate the LUN in the IDENTIFY message

### ISSUE THREAD

**Issue by uweseimet** [akuker/RASCSI#317]
This ticket results from https://github.com/akuker/RASCSI/issues/309.

The LUN field (bits in byte 1 in the CDB) was deprecated in the SCSI standard long ago. The LUN has to be selected by an IDENTIFY message instead. Rascsi ignores the LUN in the IDENTIFY message and always expects the LUN in the CDB. This is not compliant to SCSI and causes the issue reported in https://github.com/akuker/RASCSI/issues/309.

```
Oct 11 21:00:07 raspberrypi RASCSI[432]: [2021-10-11 21:00:07.648] [trace] Message code IDENTIFY $C3
Oct 11 21:00:07 raspberrypi RASCSI[432]: [2021-10-11 21:00:07.648] [trace] virtual void SASIDEV::Command() Command Phase
Oct 11 21:00:07 raspberrypi RASCSI[432]: [2021-10-11 21:00:07.648] [trace] virtual void SASIDEV::Command() Command Byte 0: $12
Oct 11 21:00:07 raspberrypi RASCSI[432]: [2021-10-11 21:00:07.648] [trace] virtual void SASIDEV::Command() Command Byte 1: $00
Oct 11 21:00:07 raspberrypi RASCSI[432]: [2021-10-11 21:00:07.648] [trace] virtual void SASIDEV::Command() Command Byte 2: $00
Oct 11 21:00:07 raspberrypi RASCSI[432]: [2021-10-11 21:00:07.648] [trace] virtual void SASIDEV::Command() Command Byte 3: $00
Oct 11 21:00:07 raspberrypi RASCSI[432]: [2021-10-11 21:00:07.648] [trace] virtual void SASIDEV::Command() Command Byte 4: $FF
Oct 11 21:00:07 raspberrypi RASCSI[432]: [2021-10-11 21:00:07.648] [trace] virtual void SASIDEV::Command() Command Byte 5: $00
Oct 11 21:00:07 raspberrypi RASCSI[432]: [2021-10-11 21:00:07.648] [trace] virtual void SCSIDEV::Execute() Execution phase command $12
Oct 11 21:00:07 raspberrypi RASCSI[432]: [2021-10-11 21:00:07.648] [debug] ++++ CMD ++++ virtual void SCSIDEV::Execute() Executing command $12
Oct 11 21:00:07 raspberrypi RASCSI[432]: [2021-10-11 21:00:07.649] [debug] virtual bool Disk::Dispatch(SCSIDEV*) Executing Inquiry ($12)
```

The command above has to be executed for LUN 3, but rascsi executes it for LUN 0.

**Comment by uweseimet** [comment]
@akuker I'm afraid I'm getting these bogus email message again ...

```
[akuker/RASCSI] Generate a RaSCSI OS image, based upon the official Rapsberry Pi
+OS workflow run

Repository: akuker/RASCSI
Workflow: Generate a RaSCSI OS image, based upon the official Rapsberry Pi OS
Duration: 11 minutes and 40.0 seconds
Finished: 2021-10-11 14:23:37 UTC

View results: https://github.com/akuker/RASCSI/actions/runs/1329317027

Jobs:
  * build failed (1 annotation)
```

**Comment by uweseimet** [comment]
@rdmark I know, but it would be good if this was tested on a separate branch. Looks as if once again any branch is affected.

**Comment by Pacjunk** [comment]
Not sure how I would do that. I just get the machine to list devices, I don't get to control how many it looks for. I'll update now and test a bit later today  (sorry timezones are slowing things down!!)

**Comment by Pacjunk** [comment]
OK. It is looking good!  With only 1 drive presented the console and OS only show one LUN  (as LUN 0). Log attached.
[Trace1.log](https://github.com/akuker/RASCSI/files/7326770/Trace1.log)

**Comment by Pacjunk** [comment]
Another log with 2 images (2 & 3) with the OS running
[Trace2.log](https://github.com/akuker/RASCSI/files/7326776/Trace2.log)
.

**Comment by uweseimet** [comment]
@Pacjunk Thanks a lot for your extensive testing. Regarding SCSI command 0x3E (READ LONG), this is not implemented by rascsi, and it is a command where the data transferred are vendor-specific. This is why it cannot really be emulated. This command is not supported by recent SCSI standard anymore, by the way.
I changed the log level of this warning to trace, because there will always be cases where a command is not supported, but also not really needed by the computer. Sometimes a driver just uses certain commands for optimizations, and if these commands are not available falls back to others.
I fixed the wrong LUN evaluation of rasctl, so that one can now also attach LUNS > 9 with rasctl.

Correct me if I am wrong, but all of your issues are resolved, aren't they?

**Comment by Pacjunk** [comment]
Pretty much. I did notice a few other things. If I accidentally removed a LUN using the GUI (bad I know), I got the error message about consecutive LUNs etc, but it would stop me from attaching a device to a totally different ID. e.g. removed 3:0, then couldnt mount a CD image on 5:0. Also could not put the deleted one back. Also If I attempted to create a non-consecutive LUN it would give me the error message, but then prevented me from attaching that file to another id:lun. Said it was already in use, when it wasn't. Luckily I had a saved configuration, so restoring that got me out of it. When I had all 32 HDDs attached, I had trouble adding a CD device with a profile. It ignored the profile and mounted as 2048 which doesnt work in my situation. Once I deleted a few LUNs, the CD attached fine. Boundary case, I know.

**Comment by uweseimet** [comment]
@Pacjunk The Atari computers with SCSI bus also use the NCR5380. Regarding the web UI @rdmark should comment. The upcoming <a href="https://www.rascsi.de/en/features.html">Rascsi Control app</a> has LUN support.

**Comment by Pacjunk** [comment]
Looks good. Thanks for all your hard work.

**Comment by uweseimet** [comment]
@Pacjunk The latest code in the lun_handling_update should address the issues with attaching/detaching from your previous comment, at least as far as the backend is concerned.
@rdmark I don't think that the limitation to 32 devices/LUNs is a backend issue. Maybe the web UI blocks adding more?

**Comment by uweseimet** [comment]
@rdmark I just committed the change that detaches all LUNs equal to or higher than the one specified:

```
rasctl -l
+----+----+------+-------------------------------------
| ID | UN | TYPE | DEVICE STATUS
+----+----+------+-------------------------------------
|  0 |  0 | SCHD | /home/pi/images/test.hds (WRITEPROTECT)
|  1 |  0 | SCRM | /home/pi/images/zip.hds
|  3 |  0 | SCMO | /home/pi/images/test.mos
|  4 |  0 | SCCD | /home/pi/images/test.iso (WRITEPROTECT)
|  5 |  0 | SCDP | DaynaPort SCSI/Link
|  5 |  1 | SCHD | /home/us/hatari/slave.hds
|  5 |  2 | SCHD | /home/us/hatari/master.hds
+----+----+------+-------------------------------------
>rasctl -i 5 -c d
>rasctl -l
+----+----+------+-------------------------------------
| ID | UN | TYPE | DEVICE STATUS
+----+----+------+-------------------------------------
|  0 |  0 | SCHD | /home/pi/images/test.hds (WRITEPROTECT)
|  1 |  0 | SCRM | /home/pi/images/zip.hds
|  3 |  0 | SCMO | /home/pi/images/test.mos
|  4 |  0 | SCCD | /home/pi/images/test.iso (WRITEPROTECT)
+----+----+------+-------------------------------------

[2021-10-12 19:28:40.873] [info] Detached SCHD device with ID 5, unit 2
[2021-10-12 19:28:40.873] [info] Detached SCHD device with ID 5, unit 1
[2021-10-12 19:28:40.873] [info] Detached SCDP device with ID 5, unit 0
```

**Comment by rdmark** [comment]
@uweseimet I've been testing the logic today, and it seems to work as expected. I also pushed webapp code to your branch to make the UI sensitive to these changes, as well as enabling attaching/detaching to specific LUNs. 

@Pacjunk has promised to run some tests in their environment today. I suggest we merge the PR once they give the green light. :)

**Comment by Pacjunk** [comment]
OK, it flushed when I copied about 1.5MB to the disk. My tests were only copying about 0.25MB to each disk just to check for writability, uniqueness etc.

**Comment by uweseimet** [comment]
@Pacjunk Anything else is related to the web UI, isn't it? I guess that @rdmark is going to take a look at it.

**Comment by uweseimet** [comment]
@Pacjunk Yes, just run "git checkout develop".

**Comment by uweseimet** [comment]
@Pacjunk I suggest that you create a ticket for this, with information on how to reproduce the caching issue. Note, though, that I am most likely not going to address this ticket, but somebody else might.
