### ISSUE TITLE
Remove multiple of 512 validation for attaching image files

### ISSUE THREAD

**Issue by rdmark** [akuker/RASCSI#319]
As discussed in #306, remove the code that prevents an image that's not a multiple of 512 to be attached as a drive in rascsi.
If the file is not a multiple of 512 bytes, rascsi will read up until the last multiple of 512 and ignore the last <512 bytes.

**Comment by rdmark** [comment]
@uweseimet This could have been a plausible cause, but stopping rascsi-web doesn't make the logging stop. I'll keep investigating.

**Comment by uweseimet** [comment]
@rdmark I would expect rascsi not to log anything if there is no client connecting to rascsi. When you ensure that nothing related to rascsi is running, and then start rascsi, is there still any logging. That's the test scenario I used, and there were no log messages.

**Comment by uweseimet** [comment]
@rdmark This should be fixed in the issue_319 branch.
