### ISSUE TITLE
Daynaport device attached with 'rasctl -f' gets superfluous 'file' parameter

### ISSUE THREAD

**Issue by rdmark** [akuker/RASCSI#339]
A recently introduced bug in develop:

> pi@pizw:~/RASCSI $ rasctl -i 6 -c attach -t scdp -f wlan0:10.10.20.1/24
> pi@pizw:~/RASCSI $ rasctl -i 6 -c s
>  6:0  SCDP  Dayna:SCSI/Link:1.4a  file=wlan0:10.10.20.1/24  interfaces=wlan0:10.10.20.1/24

The Daynaport device should not have a 'file' parameter.

**Comment by uweseimet** [comment]
@rdmark I also don't like this very much, but I don't think there is an ideal solution, so I opted for the one currently implemented.
