### ISSUE TITLE
Allow OLED script to run even if no drives are mounted

### ISSUE THREAD

**Issue by endsjustify** [akuker/RASCSI#35]
Currently rascsi_oled_monitor.py will error out if no drives are mounted:

```
Running with the following display:
<Adafruit_SSD1306.SSD1306.SSD1306_128_32 object at 0x766dcd50>

Will update the OLED display every 250ms (approximately)
Traceback (most recent call last):
  File "/usr/local/bin/rascsi_oled_monitor.py", line 151, in <module>
    output = str.strip(fields[1]) + " " + str.strip(fields[3]) + " " + os.path.basename(str.strip(fields[4]))
IndexError: list index out of range
```

This prohibits any display and also will stop the systemd service from auto-running on boot due to the script error. Demanding the user manually start the service once a drive has been mounted:

```
● monitor_rascsi.service - Monitor RaSCSI service
Loaded: loaded (/etc/systemd/system/monitor_rascsi.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Mon 2020-09-14 18:42:41 EDT; 3s ago
Process: 943 ExecStart=/usr/local/bin/rascsi_oled_monitor.py (code=exited, status=1/FAILURE)
Main PID: 943 (code=exited, status=1/FAILURE)
```

As some users may prefer on the fly mounting and not want any drives mounting automatically, it would be best if the script was able to tell no drives were mounted and instead display just the date and time and perhaps a "No Drives Mounted" message on the OLED display. 

I have temporarily resolved this by editing line 148 of rascsi_oled_monitor.py to:

`if (len(line) == 0) or line.startswith("+---") or line.startswith("| ID | UN") or line.startswith("No images"):`

**Comment by akuker** [comment]
@thewesker fixed this issue with pull request: https://github.com/akuker/RASCSI/pull/45
