### ISSUE TITLE
Creating new images through Web UI led to data loss when running out of disk storage

### ISSUE THREAD

**Issue by rdmark** [akuker/RASCSI#356]
We may need additional disk space validation when creating new disk image files.

Levo_man reported data loss when creating several images in a row when disk space was low.

**Comment by uweseimet** [comment]
@rdmark Is there any issue with creating new image files using the CREAT_IMAGE operation instead of using truncate()? CREATE_IMAGE uses fallocate(), which is a system call with well-defined error handling.

**Comment by rdmark** [comment]
I could also reproduce the issue where config files are saved as 0 byte files when disk space is full, despite getting error "[Errno 28] No space left on device". This is entirely a client side issue, and I suspect a bug in the python json library (dump class).

**Comment by uweseimet** [comment]
@rdmark Yes, rascsi should remove the created file if file creation fails. I will update the code.

**Comment by rdmark** [comment]
Fix for the webapp config file case https://github.com/akuker/RASCSI/pull/365
