### ISSUE TITLE
Create a changelog and release notes for 21-10 release

### ISSUE THREAD

**Issue by rdmark** [akuker/RASCSI#361]
Release kanban: https://github.com/akuker/RASCSI/projects/1
Release notes draft: https://github.com/akuker/RASCSI/releases/edit/untagged-44bd2233ce79eb2c6e43

**Comment by uweseimet** [comment]
@rdmark Would you agree on creating the release branch after the current PRs have been merged? I suggest a quiet period of one week (bug fixes in the release branch only) before creating the release tag and announcing the release.
In the future bugs in a release should be fixed asap on the release branch, and a bugfix release should be created.
