### ISSUE TITLE
Provide a "bootstrap.hda" file with some essentials

### ISSUE THREAD

**Issue by erichelgeson** [akuker/RASCSI#38]
* System 7.0.1
* System Picker
* LIDO 
* CD ROM driver
* StuffIt Expander
* SCSIProbe
* Patched Apple HD Setup
* Disk util

**Comment by akuker** [comment]
https://macintoshgarden.org/apps/scsiprobe

Potentially a super, bare-bones bootable System 7.1 install, with the patched CD-ROM driver included?

**Comment by erichelgeson** [comment]
http://macintoshgarden.org/apps/rascsi-68kmla-edition
