### ISSUE TITLE
Provide a way to grab a file and present it as a cdrom image

### ISSUE THREAD

**Issue by erichelgeson** [akuker/RASCSI#39]
Say you found some awesome software but there's a lot of steps to get it to your vintage mac. What if the web interface allowed you to enter a url and click a button. It could download, create an iso, and mount it so you could copy the file off.

A quick example of the moving parts would be something like:
```bash
mkdir /tmp/foo && cd /tmp/foo
wget https://macintoshgarden.org/some/file.sit.hqx
genisoimage -hfs -o software.iso /tmp/foo/
rasctl -c attach -i 3 -t cd software.iso
```

If there is a way to preserve forks that would be even better.

**Comment by rdmark** [comment]
This feature has since been implemented!  From the webui: "Download File from web and create HFS CD"
I just tested this working perfectly for grabbing a random file off the Macintosh Garden and getting it on my Mac SE through a CM image created on the fly. b32f324
