### ISSUE TITLE
Unzip should move .properties files to .config

### ISSUE THREAD

**Issue by Pacjunk** [akuker/RASCSI#392]
# Info

- Which version of Pi are you using: ZeroW
- Which github revision of software: develop
- Which board version: FULLSPEC
- Which computer is the RaSCSI connected to: VAXstation/Alphaserver

# Describe the issue

The unzip feature is great and I intend to use it to store software ISOs and extract only as required. Also to store various installed operating systems for testing. Some ISO files (like mine) and hard disk images have .properties files to set sector sizes or vendor/product strings. These should be processed if found in the zip file.

If a .properties file is detected inside the zip file, then:

- It should not be listed in the expanded zip details (or maybe put an asterisk after the image name to flag it)
- If an image is selected to unzip, the corresponding .properties file should be moved to the .config directory so that it is associated with the image.

This would allow image files to be restored correctly along with their properties.

I notice that the delete function automatically deletes the associated .properties file, so this part is already taken care of.

**Comment by rdmark** [comment]
@Pacjunk This should address this use case https://github.com/akuker/RASCSI/pull/432

What it does, is that when you choose to unzip a properties file individually, as well as as part of Unzip All, the resulting file will be moved to ~/.conf/rascsi/

Seems to be working as expected in my testing.

**Comment by rdmark** [comment]
@Pacjunk Improvements as discussed in Discord https://github.com/akuker/RASCSI/pull/447
