### ISSUE TITLE
Provide ability to download properties file

### ISSUE THREAD

**Issue by Pacjunk** [akuker/RASCSI#393]
# Info

- Which version of Pi are you using: ZeroW
- Which github revision of software: develop
- Which board version: FULLSPEC
- Which computer is the RaSCSI connected to: VAXstation/Alphaserver

# Describe the issue

This is related to #392. In the list of images where the image has a properties file and you can use the arrow to expand the details, it would be handy if there was a download button here to download the properties file. This could be combined with the download of the base image so that they could be zipped and used as in #392.

e.g. (excuse my poor image editing skills!)

![download](https://user-images.githubusercontent.com/92196260/139048420-c40147c3-cc82-4395-a460-ddde23ce98af.jpg)
)

**Comment by rdmark** [comment]
@Pacjunk Untested code in https://github.com/akuker/RASCSI/pull/432 (that should work)

Proper testing is blocked by https://github.com/akuker/RASCSI/pull/426 which needs to be merged first.
