### ISSUE TITLE
CREATE_IMAGE command has no response message

### ISSUE THREAD

**Issue by rdmark** [akuker/RASCSI#410]
The PbResult object you get back from a CREATE_IMAGE command does not seem to have a result message.
I haven't done a thorough testing of all commands yet, but this one stood out as I was refactoring the web app.
Edit: Seems to be the case also for ATTACH and LOG_LEVEL

Latest develop

**Comment by uweseimet** [comment]
@rdmark That's intentional. There is never a message if a command was executed successfully, i.e. if the result status is true because there was no error.

**Comment by rdmark** [comment]
@uweseimet Fair enough, I understand the design decision in this case. Thanks for your explanation. I will manage successful operation notifications on the client side.
