### ISSUE TITLE
Advanced User install options in easyinstall.sh

### ISSUE THREAD

**Issue by rdmark** [akuker/RASCSI#438]
To introduce options for installing rascsi without configuring the systemd services, for advanced users who prefer to run rascsi / rascsi-web manually.

**Comment by rdmark** [comment]
PR in https://github.com/akuker/RASCSI/pull/472

**Comment by rdmark** [comment]
@uweseimet Please see the PR above. Do you think this approach would be helpful to you, and others who don't want to run rascsi/rascsi-web as services?

**Comment by uweseimet** [comment]
@rdmark IMO there should be an option that does nothing except installing the required dependencies and compiling the source. It should not even create an images folder, like option 10) currently does.
I'd suggest to add a comment that tells the user why a password is required. Currently there is the "Password:" prompt without any explanation. If you start some script and this script asks you for a password, do you just enter it? You shouldn't :).

**Comment by erichelgeson** [comment]
> does nothing except installing the required dependencies and compiling the source

I'd argue if an advanced user knows enough to know they need that it seems they could just do it themselves or write an alias/script. Whatever options we choose here it seems an advanced user may have different opinions on what they want done.

An option may be to make all the individual methods here `source`able into a shell/script so advanced users could compose their own needs.

**Comment by rdmark** [comment]
@uweseimet I added an early check for sudoers privileges for the install options that touch system configuration, with a descriptive prompt message.

**Comment by uweseimet** [comment]
@rdmark Great, thank you!
