### ISSUE TITLE
not a issue , a system to add to compatibility

### ISSUE THREAD

**Issue by macphreak4evr** [akuker/RASCSI#451]
# Info please Add the Commodore Amiga 3000 to the system compatibility 

- Which version of Pi are you using: zero
- Which github revision of software: latest
- Which board version:2.3b
- Which computer is the RaSCSI connected to: Commodore Amiga 3000

# Describe the issue
no issue, works on internal 50 pin, external db25, bootable on any id that is not in use by Amiga native. shares Amiga SCSI bus. can hot add drives on the fly, removals require reboot.

**Comment by rdmark** [comment]
@macphreak4evr Thanks for letting us know that it works on your machine!  May I ask you to update the compatibility wiki page with this information? https://github.com/akuker/RASCSI/wiki/Compatibility

**Comment by rdmark** [comment]
I added the system to the list myself, while I was doing other edits to the page. Please don't hesitate to add to it.

**Comment by macphreak4evr** [comment]
Awesome thanks!

Chris Edwards 
Network Engineer
