### ISSUE TITLE
Kobold 'Cannot write FAT tables' error (Atari)

### ISSUE THREAD

**Issue by mzryz** [akuker/RASCSI#473]
# Info

- Which version of Pi are you using: Zero2 W
- Which github revision of software: develop-111920e
- Which board version: Full Spec
- Which computer is the RaSCSI connected to: Atari TT

# Describe the issue

Only when using Kobold, file transfers fail with an error when 'updating fat tables' when trying to write to RaSCSI drive (IDE to SCSI). It doesn't manage to write any files, just fails on the initial FAT table update. I tested TOS transfer by copying 2800 files from IDE to SCSI (Thunder IDE interface) There is no problem when using normal TOS. Perhaps there is something Kobold does that is not supported yet?

I wonder if @uweseimet might know.

**Comment by uweseimet** [comment]
@mzryz I am using Kobold (version 3.5.1) all the time and so far have not observe any issues. There is nothing Kobold could do that would not be supported. All in all Kobold does not do something unusual.

**Comment by mzryz** [comment]
@mzryz just to confirm: I have the TT motherboard resistors installed & termination enabled for RaSCSI. Is this correct? (only SCSI device on the machine)

**Comment by uweseimet** [comment]
@mzryz Both ends of the physical SCSI chain have to be terminated, so your setup sounds correct to me. Bad cables can also cause issues, of course.

**Comment by mzryz** [comment]
@uweseimet Ok yes I think this must be a cable issue of some kind. I just tested on my Falcon and Kobold worked fine on RaSCSI. I'll close this issue. Thank you for your advice.
