### ISSUE TITLE
Feature request: Show filename in verification dialog when deleting a file

### ISSUE THREAD

**Issue by battlehax** [akuker/RASCSI#475]
through the web ui when removing a file, maybe instead of just "Delete file?" in the popup dialog, it could include the name of the file? ie: "Are you sure you want to delete Important_mac_os_boot_disk.hda?"

**Comment by rdmark** [comment]
@battlehax Thanks for raising the ticket! This PR adds the file name to the modal: https://github.com/akuker/RASCSI/pull/476

I'm not entirely convinced about making the sentence longer though -- it feels like saying the same thing with more words. ;)
