### ISSUE TITLE
Web Interface encrypted https

### ISSUE THREAD

**Issue by rdmark** [akuker/RASCSI#489]
To introduce opt-in encrypted https for the Web Interface.

We should retain an option to use http for vintage browsers, and this should still probably be the default.

**Comment by hsiboy** [comment]
This does throw up some challenges. Are you thinking self-signed certs?

**Comment by rdmark** [comment]
Yes, I was thinking self-signed certificates. I think it should be sufficient for the purpose of preventing network packet sniffing. Do you have other suggestions?
