### ISSUE TITLE
Create a web control interface for RaSCSI

### ISSUE THREAD

**Issue by akuker** [akuker/RASCSI#5]
Create a web interface to control/interact with RaSCSI.
_**This web interface should work with old browsers! At a minimum, Netscape 4, but even older would be better.**_

A potential starting point:
https://github.com/ztto/rascsi-php

Some potential features:
* Add/remove drives
* Change removable media for CD-ROMs
* Be able to upload/manage CD-ROMs stored on the Pi
* Restart the RaSCSI service

Additional features:
* See usages statistics for the Pi, such as:
** Disk/memory/storage usage
** How many bytes transfered for each SCSI ID?
** Error logs?
* Be able to upload/manage CD-ROMs stored on the Pi

**Comment by phrax0** [comment]
Just commenting that as of 2020-08-14, the development of the web interface currently includes many of the features noted in this issue.

**Comment by akuker** [comment]
Agreed. I think this can be closed.

The following PHP interface is in place to allow web control:
https://github.com/akuker/RASCSI/tree/master/src/php

Setup instructions are here:
https://github.com/akuker/RASCSI/wiki/Web-Interface
