### ISSUE TITLE
sudo -v fails to validate in some circumstances

### ISSUE THREAD

**Issue by rdmark** [akuker/RASCSI#500]
As reported by @erichelgeson, 'sudo -v' is not able to validate in some circumstances. This is to investigate the root cause, and introduce a more portable solution.

**Comment by rdmark** [comment]
@erichelgeson I tried to reproduce with the hypothesis of a user with no password set, that's in the sudo group and NOPASSWD enabled. Alas, 'sudo -v' executes without a password prompt.

Do you have any other ideas what could be different in your environment?

**Comment by erichelgeson** [comment]
Not an issue - PEBCAK
