### ISSUE TITLE
Web Interface: support files with space in names

### ISSUE THREAD

**Issue by ewanuno** [akuker/RASCSI#53]
# Info

- Which version of Pi are you using:
- Which github revision of software:
- Which board version:
- Which computer is the RaSCSI connected to:

# Describe the issue

**Comment by ewanuno** [comment]
filenames containing spaces can not be uploaded via the web interface or if uploaded via sftp, attached via the web interface.

**Comment by rdmark** [comment]
This should work now, develop 8a3642b
Both uploading files and attaching files with spaces in their file names works for me
