### ISSUE TITLE
Add interface operation that returns operation meta data

### ISSUE THREAD

**Issue by uweseimet** [akuker/RASCSI#533]
A new interface operation OPERATION_META_DATA shall be added. This operation shall return a list of supported operations, their supported parameters, permitted values, and whether a parameter is optional or not.
This feature will reduce the client dependency on the RaSCSI version, because a client knows about supported operations without having to rely on (hard-coded in the client) RaSCSI versions.
Intelligent clients can up to a certain degree dynamically build operations, based on the meta data information. It should even be possible to build a simple generic client, which can construct and validate remote interface commands based on user input.
Optional descriptions are also provided. A non-localized client may make use of them in order to guide the user.

```
// The operation parameter meta data. The parameter data type is provided by the protobuf API.
message PbOperationParameter {
    string name = 1;
    // Optional short localized description, key is the lower case locale (e.g. en, de).
    // Falling back to "en" is recommended if a description for a particular language is missing.
    map<string, string> description = 2;
    // There is no specific set of permitted values if empty
    repeated string permitted_values = 3;
    // Optional default value. If there is no default the value is mandatory.
    string default_value = 4;
}

// The list of parameters supported by an operation
message PbOperationMetaData {
    // Optional short localized description, key is the lower case locale (e.g. en, de).
    // Falling back to "en" is recommended if a description for a particular language is missing.
    map<string, string> description = 1;
    repeated PbOperationParameter parameters = 2;
}

// Mapping of operation names to their meta data
message PbOperationInfo {
    map<string, PbOperationMetaData> operations = 1;
}
```
```
>rasctl -o
Remote operations supported by rascsi and their parameters:
  ATTACH (Attach device, device-specific parameters are required)
    name: mandatory (Image file name in case of a mass storage device)
    interfaces: mandatory (Comma-separated prioritized network interface list)
  CHECK_AUTHENTICATION (Check whether an authentication token is valid)
    token: mandatory (Authentication token to be checked)
  COPY_IMAGE (Copy image file)
    from: mandatory (Source image file name image file name)
    to: mandatory (Destination image file name)
    read_only: optional (Read-only flag)
      Permitted values: true, false
      Default value: false
  CREATE_IMAGE (Create an image file)
    file: mandatory (Image file name)
    size: mandatory (Image file size in bytes)
    read_only: optional (Read-only flag)
      Permitted values: true, false
      Default value: false
  DEFAULT_FOLDER (Set default image file folder)
    folder: mandatory (Default image file folder name)
  DEFAULT_IMAGE_FILES_INFO (Get information on available image files)
    filename_pattern: mandatory (Pattern for filtering image file names)
  DELETE_IMAGE (Delete image file)
    file: mandatory (Image file name)
  DETACH (Detach device, device-specific parameters are required)
  DETACH_ALL (Detach all devices)
  DEVICES_INFO (Get information on attached devices)
  DEVICE_TYPES_INFO (Get device properties by device type)
  EJECT (Eject medium, device-specific parameters are required)
  IMAGE_FILE_INFO (Get information on image file)
    file: mandatory (Image file name)
  INSERT (Insert medium, device-specific parameters are required)
    file: mandatory (Image file name)
  LOG_LEVEL (Set log level)
    level: mandatory (New log level)
  LOG_LEVEL_INFO (Get log level information)
  MAPPING_INFO (Get mapping of extensions to device types)
  NETWORK_INTERFACES_INFO (Get the available network interfaces)
  OPERATION_INFO (Get operation meta data)
  PROTECT (Protect medium, device-specific parameters are required)
  PROTECT_IMAGE (Write-protect image file)
    file: mandatory (Image file name)
  RENAME_IMAGE (Rename image file)
    from: mandatory (Source image file name)
    to: mandatory (Destination image file name)
  RESERVED_IDS_INFO (Get list of reserved device IDs)
  RESERVE_IDS (Reserve device IDs)
    ids: mandatory (Comma-separated device ID list)
  SERVER_INFO (Get rascsi server information)
    filename_pattern: mandatory (Pattern for filtering image file names)
  SHUT_DOWN (Shut down or reboot)
    mode: mandatory (Shutdown mode)
      Permitted values: rascsi, system, reboot
  START (Start device, device-specific parameters are required)
  STOP (Stop device, device-specific parameters are required)
  UNPROTECT (Unprotect medium, device-specific parameters are required)
  UNPROTECT_IMAGE (Make image file writable)
    file: mandatory (Image file name)
  VERSION_INFO (Get rascsi server version)
```

**Comment by rdmark** [comment]
@uweseimet Do I understand this feature correctly with, say, this scenario: The very latest Android app trying to talk to a somewhat old RaSCSI server, and dynamically hides UI options for features that the server does not understand.

**Comment by uweseimet** [comment]
@rdmark This is useful for any client, but the web ui is least likely to profit.
A client can query rascsi for the operations supported, and can react on it. Typical scenario: A client is aware of the SHUT_DOWN operation (and offers it to the user), but is connected to an old rascsi version that does not support this operation. In this case the client should not offer the SHUT_DOWN operation at all, because it will definitely fail. Checking the rascsi version in order to find out which operation is supported is not that good, because sooner or later the client ends up with checking many versions. And if, in a future version of rascsi, an operation is not available anymore, it gets even more difficult when using version numbers.
Instead, the client can use OPERATION_INFO to explicitly find out the operations supported by the rascsi server the client is currently connected to. (Future versions of my app will most likely support a selectablle set of rascsi instances, which is useful for users who have more than one board.) Up to a certain degree a client can even use operations not yet supported by this client, because it knows operation names and parameters. But this use is rather exotic.

**Comment by uweseimet** [comment]
@rdmark Just a note: There is one more feature that does not depend on the RaSCSI version, but on how RaSCSI was started, namely the shutdown/reboot. When started with sudo all modes (rascsi, shutdown, reboot) are available. But when not started as root (unusual case, but as you know I do most of my testing on a PC, where you do not need to be root because no RaSCSI hardware is present), the meta data signal that only the "rascsi" shutdown mode is available. A client can react on this by not offering the unavailable shutdown modes.
