### ISSUE TITLE
Finalize localization of rascsi error messages

### ISSUE THREAD

**Issue by uweseimet** [akuker/RASCSI#559]
A few rascsi error messages still do not use the localization feature. Affected pieces of code are where ReturnStatus() instead of ReturnLocalizedError() is called in case of an error.

**Comment by rdmark** [comment]
@uweseimet Is there anything left to do here?

**Comment by uweseimet** [comment]
@rdmark In some cases ReturnLocalizedError() is not yet called. This has to be updated, and localizations added.

**Comment by n4al** [comment]
At least one of the (ReturnStatus) messages in src/raspberrypi/rascsi_image.cpp is printed out in the Web UI. This is an issue in case the language of the Web UI is not English. For example:

![Captura de pantalla 2022-09-07 a las 15 37 33](https://user-images.githubusercontent.com/731358/188947850-23de03a7-cda8-4eb1-869a-6897ffe120a0.png)

**Comment by uweseimet** [comment]
@rdmark rascsi.cpp now uses the localizer for all messages. This was the goal of this ticket. If you would like to add other languages than English or German for the new localized messages please create a new ticket.
