### ISSUE TITLE
Authentication token revealed in RASCSI info level logs

### ISSUE THREAD

**Issue by rdmark** [akuker/RASCSI#563]
Whenever a command is being executed, the authentication token is revealed in plain text in the info level logs:

```Dec 24 09:32:29 rascsi3b RASCSI[820]: [2021-12-24 09:32:29.803] [info] Executing: operation=ATTACH, command params='token=foobar', device id=6, unit=0, type=SCCD, vendor='', product='', revision='', block size=0```

I think this is a security hole, if a malicious actor gets access to syslog.

**Comment by uweseimet** [comment]
@rdmark Indeed, going to fix this asap, latest tomorrow.

**Comment by rdmark** [comment]
Nice fix. Verified that the token shows up as ??? in the logs.
