### ISSUE TITLE
Create version 21.12 release tag and build new image

### ISSUE THREAD

**Issue by akuker** [akuker/RASCSI#574]
- Create a new release tag - v21.12.01
- Generate a new raspberry pi OS image
- Create build release notes

**Comment by akuker** [comment]
@uweseimet @rdmark @bzeiss - I'm planning on tagging version 21.12 on Wednesday (December 29) afternoon. Let me know if this doesn't work for you guys.

**Comment by rdmark** [comment]
I have no concerns with this release date.
It may not be enough time for folks to add another localization, however.

**Comment by bzeiss** [comment]
All good for me.

**Comment by uweseimet** [comment]
Also fine for me.

**Comment by akuker** [comment]
Since there are still PRs trickling in for the localization stuff, I'm going to hold off on doing the release for a few days.

**Comment by uweseimet** [comment]
I recommend to follow the usual release procedures and create a release branch in time, which is open for bug fixes only. This guarantees that changes/PRs related to the develop branch do not affect the upcoming release.
