### ISSUE TITLE
DaynaPort: RetrieveStats doesn't provide real data

### ISSUE THREAD

**Issue by akuker** [akuker/RASCSI#600]
The RetrieveStats SCSI command to the DynaPort SCSI/Link is supposed to return the following information:
 * Frame alignment errors
 * CRC Errors
 * Frames Lost
However, the current implementation just returns 0 for all of these values.

The RaSCSI emulation could be udpated to provide some meaningful information in these fields. Frame alignment & frames lost don't really make sense, since those errors should be handled by the Linux network stack. However, they could be used to report other diagnostic information, such as the number of frames received and the number filtered out.

This should be considered a low priority issue, since this data doesn't appear to be used for anything other than statistical reporting in the DaynaPort software utilities.

**Comment by uweseimet** [comment]
Closed since this has already been flagged WONTFIX long ago.
