### ISSUE TITLE
Works on my VAXStation 4000 model 60!

### ISSUE THREAD

**Issue by jeroenbrons** [akuker/RASCSI#605]
# Info

- Which version of Pi are you using:
- Pi 3B
- Which github revision of software:
- 21.12.-1 c19c814
- Which board version:
- the one from SamplerSpa (2,4 if i'm memory serves right
- Which computer is the RaSCSI connected to:
DEC VAXStation 4000/60

# Describe the issue
Just wanted to notify that the RASCSI works fine on my DEC VAXStation 4000/60 
tested with installing and booting OpenVMS 7.3

**Comment by Pacjunk** [comment]
As expected, but good to confirm!

**Comment by uweseimet** [comment]
@jeroenbrons Please add your hardware to the RaSCSI compatibility list, so that we can close this ticket.

**Comment by rdmark** [comment]
Added to wiki https://github.com/akuker/RASCSI/wiki/Compatibility#System_compatibility
