### ISSUE TITLE
Web interface suggestion: Allow downloading of images too

### ISSUE THREAD

**Issue by kraptv** [akuker/RASCSI#62]
# Info

- Which version of Pi are you using: Raspberry Pi 4 4GB Model B
- Which github revision of software: 524f1c7
- Which board version: 2.3 FULLSPEC
- Which computer is the RaSCSI connected to: Quadra 700 and PowerMac 8500

# Describe the issue

Uploading disk images via the web is a nice handy and user-friendly way of managing images from a user standpoint. The available images are then ready to be attached and used.  

If you're already listing the images, why not make them available to download as well?  A use case of this could be:

User downloads a disk image that requires some sort of change/update from within MacOS.

User downloads disk image from a remote website / colleague / friend and then goes to the rascsi web-interface and uploads.
User attaches disk image to a SCSI ID, mounts, does whatever tweaks-updates-population to that disk image, and then disconnects the SCSI image.   Why couldn't the user just download that updated image  (and possibly send it back to their remote collaborators, etc.)

This would help in interface consistency and make the RaSCSI device a more 'embedded SCSI storage system'.

Thinking in these terms could open itself up to a "click to update" web button too but is way out of the scope of what I'm asking for here.

**Comment by akuker** [comment]
This feature was pulled in with Pull Request #69. I believe this issue can be closed now.
