### ISSUE TITLE
Man page change from /usr/share/man1 to /usr/local/man1 misses a cleanup of /usr/share/man1

### ISSUE THREAD

**Issue by bzeiss** [akuker/RASCSI#621]
It seems that in November the man page path in the Makefile was changed form /usr/share/man/man1 to /usr/local/man/man1. /usr/share/man/man1 takes precendence over /usr/local/man/man1 and the change didn't contain any cleanup of the old man page in /usr/share/man/man1. As a side-effect, rascsi versions installed before that change that updated to more recent versions will be stuck on that old man page as long as it isn't cleaned up.

It came up when I tried to look up the rasctl parameter for the token and noticed that there was no help in the man page on that parameter on my raspi.

Also, the parameter -P isn't listed on the command line help.

**Comment by rdmark** [comment]
Tested and merged! Thanks @bzeiss for the quick fix.
