### ISSUE TITLE
Switch to Netatalk 2.x

### ISSUE THREAD

**Issue by rdmark** [akuker/RASCSI#623]
Pivot to using a release from [Netatalk 2.x ](https://github.com/rdmark/Netatalk-2.x)instead of the old Netatalk-Classic release we use now.

**Comment by rdmark** [comment]
Prepared release tag https://github.com/rdmark/Netatalk/releases/tag/netatalk-2-2-220101

**Comment by akuker** [comment]
@rdmark - can this be closed?

**Comment by rdmark** [comment]
Yes! Thanks!
