### ISSUE TITLE
SCHS: Trigger script/binary execution on the Pi with a SCSI command

### ISSUE THREAD

**Issue by uweseimet** [akuker/RASCSI#648]
The RaSCSI host services (SCHS) shall be extended to execute a script/binary on the Raspberry Pi. The MANAGEMENT_PROTOCOL_OUT SCSI command or a vendor-specific SCSI command (the most flexible approach) might be a candidate for the required SCSI command.

Requirements/Ideas:

- The command and its arguments have to be passed. There should not be a limit on the size of the command payload. (This may require a vendor-specific SCSI command.) All in all the data from the SCSI command result in a system() call,
- The UID (and GID?) to use for the executed command can be provided. Default is 0 (root), which is not a security risk, because there is no way to trigger command execution by any other means than a computer connected to the same SCSI bus.
- The exit code of the command (and maybe output to stdout) shall be returned as a result of the SCSI command. There may be commands that do not terminate. This is why oneway semantics (equivalent to starting a command in the background) shall be supported. In such a case the PID of the command shall be returned to the client, so that it can later (with another command) refer to this PID.

**Comment by akuker** [comment]
> * Default is 0 (root), which is not a security risk, because there is no way to trigger command execution by any other means than a computer connected to the same SCSI bus.

I agree, this isn't really a security risk. 

Do you have any example use cases for this feature?

An interesting extension to this would be to access the 'rasctl'-like functions. One could develop a host application that would do the same functionality as the android/web apps, but going through the scsi bus.

**Comment by uweseimet** [comment]
@akuker No, no examples yet from my side. This ticket is in an early stage. If nobody finds any example use case it should not be implemented. Typical examples would be cases where the Pi can do work for SCSI clients.

**Comment by uweseimet** [comment]
Still no ideas on meaningful binaries/scripts that could be executed, so I am going to close this ticket.
