### ISSUE TITLE
Enhancement to RaSCSI Android app

### ISSUE THREAD

**Issue by timmcross** [akuker/RASCSI#659]
# Info

- Which version of Pi are you using:
- Which github revision of software:
- Which board version:
- Which computer is the RaSCSI connected to:

# Describe the issue
Just curious if an option to shutdown the Pi can be added to the Android RaSCSI app?  Think that would be easier than going to the web interface everytime.

**Comment by uweseimet** [comment]
@timmcross The feature already exists. It's the bottom right icon in the server information.

By the way, please note that this site is not a support site for the RaSCSI control app. The control app is a separate project.
