### ISSUE TITLE
Bootup gets stuck in same place

### ISSUE THREAD

**Issue by roses2uk** [akuker/RASCSI#673]
# Info

- Which version of Pi are you are using Pi Zero 2
- Which github revision of software: Latest 6/2/22
- Which board version: 2.4a
- Which computer is the RaSCSI connected to: n/a

# Describe the issue
First time using Pi Zero with a RaSCSI. Used Rasp Pi Imager in Windows to write the image and I checked set host name, SSH, added password, my WiFi details, etc in the Settings page.

Am using an HDMI monitor to see what's happening during boot. Always gets stuck at "finished update UTMP about system run level changes". If rebooted, doesn't even get past the login pw line. Have no USB adapter for my keyboard or mouse.

Get same result using releases from Nov and Dec 21.

What am I doing wrong?

**Comment by akuker** [comment]
HI @roses2uk - would you be able to post a screenshot of what you're seeing? 

Does it behave differently without the RaSCSI attached?
