### ISSUE TITLE
Using Zip disk images

### ISSUE THREAD

**Issue by roses2uk** [akuker/RASCSI#678]
# Info

- Which version of Pi are you using:
- Which github revision of software:
- Which board version:
- Which computer is the RaSCSI connected to:

# Describe the issue
On Keith Meiere's Llamamusic page are some Zipdisk files for the W30 which I would like to try. How do I upload and assign them to a SCSI ID on RaSCSI? http://llamamusic.com/s50s550/ZIPdisk-1_TOC.html

**Comment by akuker** [comment]
It appears that these zip disks can also be used as hard disk images. You should be able to download these zip files, then attach them in RaSCSI as if they were hard disks.

Note that the Github issues are generally to request features/updates/fixes to the RaSCSI software itself. For support, I'd recommend connecting to Discord: https://discord.gg/PyS58u6 There is a large community of sampler users who are extremely helpful in answering questions.

Thanks!
-Tony

**Comment by akuker** [comment]
Closing this issue, since it is a support request, not an issue with the RaSCSI.
