### ISSUE TITLE
Releasing reserved IDs in rasctl is not user friendly

### ISSUE THREAD

**Issue by rdmark** [akuker/RASCSI#691]
In the latest develop (and earlier):

From reading the man page for rasctl for the '-r' option, it is not clear how to release reservations. Through experimentation, ```rasctl -r ""``` seems to release all reservations. I think either updating the documentation, or introducing a separate  "release reservations" command would be appropriate.

**Comment by rdmark** [comment]
@uweseimet What are your thoughts here?

**Comment by uweseimet** [comment]
@rdmark I just updated the manpages which a note on the meaning of an empty list. I would not want to add a new command for this, because with the existing command you can easily release all reservations. If you know how :). But that's now mentioned in the manpage.

**Comment by uweseimet** [comment]
@rdmark One more note on this:

**Comment by rdmark** [comment]
@uweseimet Thanks for the quick fix!
