### ISSUE TITLE
minor issue variable

### ISSUE THREAD

**Issue by marcelv-3** [akuker/RASCSI#712]
# Info

- Which version of Pi are you using: 3
- Which github revision of software: latest
- Which board version: 2
- Which computer is the RaSCSI connected to: mac

# Describe the issue
minor bug in source, syncoffset instead of syncperiod
					// Transfer period factor (limited to 50 x 4 = 200ns)
						scsi.syncperiod = scsi.msb[i + 3];
						if (scsi.syncperiod > 50) {
							scsi.**syncoffset** = 50;
						}

**Comment by uweseimet** [comment]
@marcelv-3 Thank you for pointing this out. I just prepared a fix as part of https://github.com/akuker/RASCSI/pull/699.
