### ISSUE TITLE
Shouldn't you give GIMONS some of your donation?

### ISSUE THREAD

**Issue by 110-kenichi** [akuker/RASCSI#770]
Shouldn't you give GIMONS some of your donation?

https://twitter.com/tomcatzzzz/status/1545872364155863040

**Comment by akuker** [comment]
I am happy to share some (or all) of the donations with him. I have nothing but respect for GIMONS and have only been trying to spread adoption of this awesome project to other people/areas. 

However, this is a matter of discussion between GIMONS and me. I have reached out to GIMONS directly through twitter. 

If you contributed to the original project and don't feel that I have properly credited your contributions, please message me directly.
