### ISSUE TITLE
Compile time error in unarchiver.py

### ISSUE THREAD

**Issue by Pacjunk** [akuker/RASCSI#800]
# Info

- Which version of Pi are you using: Zero W  (Buster)
- Which github revision of software: develop as at time of posting
- Which board version: Fullspec
- Which computer is the RaSCSI connected to: n/a

# Describe the issue

I believe this stems from the code introduced in #789. When I compile from the develop branch, I get the following message:

```
Aug 21 12:28:30 raspberrypi RASCSIWEB[1869]:   File "/home/pi/RASCSI/python/common/src/util/unarchiver.py", line 82
Aug 21 12:28:30 raspberrypi RASCSIWEB[1869]:     if line_matches := match(unar_file_extracted, line):
Aug 21 12:28:30 raspberrypi RASCSIWEB[1869]:                      ^
Aug 21 12:28:30 raspberrypi RASCSIWEB[1869]: SyntaxError: invalid syntax
```

From discussions on discord, it appears that this syntax is only valid for Python 3.8 and later, and buster is using V3.7.3 by default.

The code either needs to be made 3.7 compliant, or the default Python version upgraded.

**Comment by secretagentmoof** [comment]
:= is indeed 3.8 syntax (see pep 572 and/or https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions )
