### ISSUE TITLE
Remove foo.hda

### ISSUE THREAD

**Issue by uweseimet** [akuker/RASCSI#816]
foo.hda appears to be a binary file with only 0 values. It does not appear to be used anymore, so it should be deleted. Storing binary files in git is not recommended anyway.
If I am mistaken and it is needed somewhere, it should be generated on the fly, e.g. with dd.

**Comment by uweseimet** [comment]
@rdmark @akuker In case this file is obsolete it should be deleted immediately.

**Comment by rdmark** [comment]
I'm not aware of any current use of this file. I think it can be removed.
