### ISSUE TITLE
Use the PI's MAC address as the DaynaPort's MAC address

### ISSUE THREAD

**Issue by uweseimet** [akuker/RASCSI#860]
Currently there is a TODO because the DaynaPort emulation uses a hard-coded MAC address. IMO the only alternative to use a hard-coded address is the use the PI's MAC address. In theory you can make it configurable, but what would be the default, and would any user know which (valid) MAC address to use in her/his network?
Would there be any issues with this solution, i.e. with using the PI's MAC address?

**Comment by uweseimet** [comment]
@rdmark My impression is that you know much more about networking than I do. Do you think my suggsted solution would cause any issues?

**Comment by rdmark** [comment]
@uweseimet I'm hardly an expert either, but wouldn't using the RPis MAC address as-is lead to conflicts when both the RPi and the computer using the DaynaPort emulation are connected to the same network?

There is one solution discussed in https://github.com/akuker/RASCSI/issues/598 where the MAC address is derived from the RPi's. This seems like a more sound approach to me.

**Comment by uweseimet** [comment]
@rdmark I missed thi other ticket, thank you for pointing this out. I will close this ticket, because it is effectiveyl a duplicate.
