### ISSUE TITLE
DELETE_IMAGE command doesn't work after recent code changes

### ISSUE THREAD

**Issue by rdmark** [akuker/RASCSI#943]
A recent code change caused the DELETE_IMAGE command to fail with ```it is currently being used by device ID -1, LUN -1```

**Comment by rdmark** [comment]
@uweseimet This might be related to the intermittent UT failure that you saw

**Comment by uweseimet** [comment]
@rdmark This is fixed with https://github.com/akuker/RASCSI/pull/944, but why the unit tests failed in one of my folders is not clear. They should always yield consistent results.
