### ISSUE TITLE
documentation: Raspberry Pi Zero

### ISSUE THREAD

**Issue by jeremybernstein** [akuker/RASCSI#98]
# Info

- Which version of Pi are you using: Zero
- Everything else: latest, but doesn't matter

# Describe the issue

- Please update the documentation to mention that the Raspberry Pi Zero orientation shown in the assembly instructions assumes that the pin headers are soldered on the back of the Raspberry Pi Zero. Typically (and in the WH version of the Zero), these are soldered to the "front" of the Zero, whereas the RaSCSI needs them on the back. The careful builder who checks to ensure that pin 1 == pin 1 when mating the two boards will notice this, but in the spirit of making documentation as helpful and explicit as possible, and in the interest of anticipating the foibles of less careful builders, so that they don't have to spend an hour desoldering pin headers (not that I speak from personal experience...), it would be useful to have it spelled out. Thanks!

**Comment by phrax0** [comment]
Hey Jeremy,
 
Thank you for the suggestion.  Looks like you and @akuker connected, and you've already updated the wiki. Thank you for making those changes, it does help clarify the instructions for the Pi Zero configuration.  If you see any other aspects of the wiki that need improvement, feel free to make them.
