### ISSUE TITLE
Feature Request: Add the hardware version at the bottom of the Web UI

### ISSUE THREAD

**Issue by akuker** [akuker/RASCSI#980]
# Info

It might be useful information to put the version of the host Raspberry Pi device at the bottom of the RaSCSI web UI. In some cases there are multiple versions of Pi hardware and this would be an easy way for users to confirm what version they have.

I believe its as simple as `cat /proc/device-tree/model` to get this information.

![image](https://user-images.githubusercontent.com/34318535/201421705-751a1155-4e8b-4235-9018-5525c228a195.png)
![image](https://user-images.githubusercontent.com/34318535/201421730-14127651-22de-48ac-af35-cf1e21abe8e3.png)

**Comment by akuker** [comment]
Note: This will not work on x86 hosts. `/sys/devices/virtual/dmi/id/sys_vendor` and `/sys/devices/virtual/dmi/id/product_name` would be an alternative.

![image](https://user-images.githubusercontent.com/34318535/201428637-4578610d-138d-480e-9e08-7b1220410565.png)

**Comment by rdmark** [comment]
@akuker Please have a look at https://github.com/akuker/RASCSI/pull/989 !
