### ISSUE TITLE
Enhancement - Mount ISO files from a compressed zip/7z archive

### ISSUE THREAD

**Issue by pacific202** [akuker/RASCSI#99]
This is for sampler users that will have a large number of ISO files that they will want to use.  Many have dozens, some of us will have hundreds.

It would be great if raSCSI could do inline unzipping as an image is mounted so we could maximize SD storage capacity.

**Comment by phrax0** [comment]
Hey pacific202, 

Thank you for your enhancement request. At this time it would be more viable to purchase a larger SD card, or use the ZFS or BTRFS filesystem and turn on compression. While adding zip/7z compression/decompression into RaSCSI is possible, the features currently in development along with bug fixes are keeping everyone busy.

However, you are welcome to submit a pull request and add this functionality yourself.
